"""
Automatically generate an image of all of the docking scores generated by
vina. This can guide your choice of cutoff when extracting results.

Usage:
    python plot.py param.yaml

The input parameters should be specified in a yaml file, see the example
folder for details.
"""


if __name__ == "__main__":
    from sys import argv
    from yaml import load, SafeLoader
    from sweep.helper import get_parameters, get_energies
    from os.path import join
    from matplotlib import pyplot as plt
    from warnings import warn

    # Read in the parameters.
    param = get_parameters(argv)

    # Read in the list of logfiles.
    with open(join(param["work_dir"], "data.yaml"), "r") as ifile:
        logs = load(ifile, Loader=SafeLoader)

    # Extract the energies.
    energies = []
    for lg in logs:
        try:
            energies += get_energies(lg)
        except StopIteration:
            warn("Logfile appears to not be finished\t"+lg, UserWarning)
            continue
        except FileNotFoundError:
            warn("Logfile not found\t"+lg, UserWarning)
            continue

    # Generate the plot
    fig, axs = plt.subplots(1, 1)
    axs.plot(sorted(energies, reverse=True), 'x')
    axs.set_xlabel("Sorted Pose", fontsize=12)
    axs.set_ylabel("Energy", fontsize=12)

    plt.show()
